version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: my-node-app
#     depends_on:
#       - postgres
#     environment:
#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_NAME: postgres
#       DB_USER: postgres
#       DB_PASSWORD: mysecretpassword

# volumes:
#   postgres-data:
